[meta]
name = "Checkpoint Times"
author = "zayshaa"
category = "Testing"

version = "9001"

[script]
imports = [ "Icons.as" , "Formatting.as", "Time.as", "lib\\Panels.as", "lib\\ZUtil.as", "lib\\CpDataManager.as", "lib\\GameState.as"]
