[meta]
name = "Checkpoint Times"
author = "zayshaa"
category = "HUD"

version = "1.2.1"

[script]
dependencies = [ "VehicleState", "ZayUtils" ]
imports = [ "Icons.as" , "Dialogs.as" , "Formatting.as", "Time.as"]
